[tool.black]
exclude = '''
/(
    .*\.egg-info
    | .*build
    | \.eggs
    | \.git
    | \.pytest_cache
    | \.tox
    | \.venv
    | \.vscode
    | dist
)/
'''
include = '\.pyi?$'
preview = true
target-version = [
    "py310",
    "py37",
    "py38",
    "py39",
]

[tool.nbqa.addopts]
black = ["--line-length=85"]
ruff = [
    "--extend-ignore=B018",
    "--extend-ignore=C408",
    "--extend-ignore=C90",
    "--extend-ignore=D",
    "--extend-ignore=N806",
    "--extend-ignore=N816",
    "--extend-ignore=PLR09",
    "--extend-ignore=PLR2004",
    "--extend-ignore=PLW0602",
    "--extend-ignore=PLW0603",
    "--line-length=85",
]

[tool.nbqa.exclude]
flake8 = "^docs/appendix/benchmark.ipynb"

[tool.pytest.ini_options]
addopts = [
    "--color=yes",
    "--doctest-continue-on-failure",
    "--doctest-modules",
    "--durations=3",
    "--ignore=docs/conf.py",
    "-m not slow",
]
filterwarnings = [
    "error",
    "ignore:.*argument to NotebookFile is deprecated.*:pytest.PytestRemovedIn8Warning",
    "ignore:the imp module is deprecated in favour of importlib.*:DeprecationWarning",
]
markers = [
    "slow: marks tests as slow (select with '-m slow')",
]
norecursedirs = [
    ".ipynb_checkpoints",
    "_build",
]
testpaths = [
    "src",
    "tests",
]

[tool.pyright]
reportGeneralTypeIssues = false
reportImportCycles = false
reportMissingParameterType = false
reportMissingTypeArgument = false
reportMissingTypeStubs = false
reportPrivateImportUsage = false
reportUnknownArgumentType = false
reportUnknownLambdaType = false
reportUnknownMemberType = false
reportUnknownParameterType = false
reportUnknownVariableType = false
reportUnnecessaryIsInstance = false
reportUnusedClass = true
reportUnusedFunction = true
reportUnusedImport = true
reportUnusedVariable = true
typeCheckingMode = "strict"

[tool.ruff]
extend-select = [
    "A",
    "B",
    "BLE",
    "C4",
    "C90",
    "D",
    "EM",
    "ERA",
    "FA",
    "I",
    "ICN",
    "INP",
    "ISC",
    "N",
    "NPY",
    "PGH",
    "PIE",
    "PL",
    "Q",
    "RET",
    "RSE",
    "RUF",
    "S",
    "SIM",
    "T20",
    "TCH",
    "TID",
    "TRY",
    "UP",
    "YTT",
]
ignore = [
    "D101",
    "D102",
    "D103",
    "D105",
    "D107",
    "D203",
    "D213",
    "D407",
    "D416",
    "E501",
    "SIM108",
]
show-fixes = true
target-version = "py37"
task-tags = ["cspell"]

[tool.ruff.per-file-ignores]
"docs/*" = [
    "E402",
    "INP001",
    "S101",
    "S113",
    "T201",
]
"scripts/*" = ["INP001"]
"setup.py" = ["D100"]

[tool.ruff.pydocstyle]
convention = "google"
